### ISSUE TITLE
Why UpdateSource task?

### ISSUE THREAD

**Issue by christianacca** [KevinMarquette/PlasterTemplates#17]
After the build I notice that *module*.psd1 source file is overwritten with the generated one from the output directory.

I then have to remember to discard the changes that are made (the version number and the explicit list of functions to export).

Neither of these changes *need* to be included in the source file as they can be computed. I specifically do *not want* these changes to be included in the source file so as to reduce merge conflicts when branching.

So to that end are you happy for me to remove the `UpdateSource` from the `module.build.ps1`?

**Comment by KevinMarquette** [comment]
I would want to keep that task for now, but we can make it not be automatic. So remove it from the default or build task.

**Comment by christianacca** [comment]
Ok cool will do
