### ISSUE TITLE
PSScriptAnalyzer rules run the slow way

### ISSUE THREAD

**Issue by KevinMarquette** [KevinMarquette/PlasterTemplates#24]
Need to rework the PSScriptAnalyzer to not enumerate each rule the way it does. I have found a better pattern where you invoke PSScriptAnalyzer once per file (instead of once per rule per file). If there are no issues, create a passing `It` statement. If it fails, enumerate the output and create a failing `It` statement for each item. 

For bootstrapping existing modules, it's easy to make those failing tests pending or skipped if needed.

**Comment by christianacca** [comment]
Sounds good

**Comment by christianacca** [comment]
Is this ready to be merged to master?
