### ISSUE TITLE
Consider using Gitversion to do calculate semantic version

### ISSUE THREAD

**Issue by christianacca** [KevinMarquette/PlasterTemplates#4]
Hi Kevin,

Have you considered using [GitVersion tool](http://gitversion.readthedocs.io/en/latest/) to calculate the next semantic vs based on git commit messages?

I've seen the approach you take [here](https://kevinmarquette.github.io/2017-10-14-Powershell-module-semantic-version/?utm_source=blog&utm_medium=blog&utm_content=titlelink) - it's very nice.

But... I think that having a file (finger print) checked into vs control will cause a head ache if you have to support production branches rather than just always deploying from master. My concern - this file will add friction in the form of "merge hell".

Christian

**Comment by KevinMarquette** [comment]
Thank you for your suggestion. That file is a big concern for me too. I don't like it either, but I have not found a cleaner solution. I will definitely look into the GitVersion tool.

I am playing with a second idea of either using tests from the previous release or checking out the previous release and re-running the fingerprint to get it on the fly.

**Comment by christianacca** [comment]
That's sounds like a good plan to me

**Comment by christianacca** [comment]
Been looking at the fingerprint logic and I think there is non-obvious implication to how it works (*please correct me if I'm wrong*). Most of the time the **logic will miss feature changes** and always bump the patch version.

Take the following typical scenario...

1. I write a new function
2. I run the build locally
    * this generates the fingerprint file which now includes the new function
3. I commit the changes that are pending in my working directory (ie new function and the fingerprint file); I use the commit message '!deploy' to trigger the deploy
4. The build runs on the CI server:
    * it compares the current list of functions (includes the new function) with the fingerprint file (also includes the new function)
    * determines that there are no new features, as the new function is seen in both the current command list and the fingerprint file
    * bumps the patch version

## Possible solutions

### 1. Commit *fingerprint* only *after* a deploy

That's a pain to remember.

### 2. Generate the fingerprint from the previous version of the module

To really fix this, the calculation logic needs to install the previous version of the module, generating a fingerprint from this. It can then compare this with a fingerprint calculated from the current module.

The trick would be:
* make sure this happens only when required (similar to how you're avoiding fetch the module version all the time from psgallery)
* make sure to use another powershell host environment to load the previous version ([this](https://github.com/RamblingCookieMonster/BuildHelpers/blob/master/BuildHelpers/Public/Set-ModuleFunctions.ps1#L50-L60) looks like an example of the essentials of how to do this)
* use `Save-Module` rather than install module to get the previous version of the module onto disk
